unbind c-b
set-option -g prefix c-a
bind-key c-a send-prefix

set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:tc"

set -g history-limit 50000
set -g base-index 1
setw -g pane-base-index 1
set -g status-interval 5
set-window-option -g mode-keys vi

set-option -g default-shell /opt/homebrew/bin/fish
#set-option -g default-command "/opt/homebrew/bin/nu --config ~/.config/nushell/config.nu"

bind r source-file ~/.config/tmux/tmux.conf
bind-key -r f run-shell "tmux neww tmux-sessionizer"

set -g @catppuccin_flavor "latte"
set -g @catppuccin_window_status_style "rounded"

# load catppuccin
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
